repos:
-   repo: local
    hooks:
      - id: black
        name: black
        entry: black.main
        language: python
        types: [python]
        require_serial: true
        stages: [pre-commit]
        additional_dependencies: [black==23.3.0]
      - id: ruff
        name: ruff
        entry: ruff.cli.main
        language: python
        types: [python]
        require_serial: true
        stages: [pre-commit]
        additional_dependencies: [ruff==0.0.275]
      - id: mypy
        name: mypy
        entry: mypy.main
        language: python
        types: [python]
        require_serial: true
        stages: [pre-commit]
        additional_dependencies: [mypy==1.3.0]