name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  install-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Unshallow the repo so versioningit can access full git history
          fetch-tags: true

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install project with dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
          pip freeze
          ls *
          exchange-automator -v

      - name: Run tests (Python 3.8)
        run: |
          pytest -vv

      - name: Check formatting (Python 3.8)
        run: black --check exchange_automator tests

      - name: Lint code (Python 3.8)
        run: ruff exchange_automator tests

      - name: Type check (Python 3.8)
        run: mypy exchange_automator