name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project with dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run unit + system tests
        run: |
          pytest

      - name: Check formatting with Black
        run: |
          black --check exchange_automator tests

      - name: Lint code with Ruff
        run: |
          ruff exchange_automator tests

      - name: Type check with mypy
        run: |
          mypy exchange_automator
